version: "3"

volumes:
    app-db-data:

services:
    traefik:
        image: traefik:v2.5
        command:
            - "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        restart: always
        ports:
            - "8000:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    db:
        image: postgres:13-alpine
        expose:
            - 5432
        volumes:
            - app-db-data:/var/lib/postgresql/data/pgdata
        env_file:
            - .env
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata

    redis:
        image: redis:alpine
        expose:
            - 6379
        env_file:
            - .env
    web:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            APP_MODULE: api.main:app
            PRE_START_PATH: scripts/prestart.sh
        depends_on:
            - db
            - redis
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.fastapi.rule=Host(`localhost`)"
